// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using umami.Infra.Data.Context;

#nullable disable

namespace umami.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206171803_tabelaTipoPagamento")]
    partial class tabelaTipoPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("umami.Domain.Entities.ITENSVENDA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("QUANT")
                        .HasColumnType("int");

                    b.Property<int>("SEQPRODUTO")
                        .HasColumnType("int");

                    b.Property<int>("SEQVENDA")
                        .HasColumnType("int");

                    b.Property<decimal>("VALOR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("SEQPRODUTO");

                    b.HasIndex("SEQVENDA");

                    b.ToTable("ITENSVENDA");
                });

            modelBuilder.Entity("umami.Domain.Entities.PRODUTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("STATUS")
                        .HasColumnType("bit");

                    b.Property<decimal>("VALOR_VENDA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("umami.Domain.Entities.TIPOPAGAMENTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TIPOPAGAMENTO");
                });

            modelBuilder.Entity("umami.Domain.Entities.TIPOUSUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DESCRICAO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TIPOUSUARIO");
                });

            modelBuilder.Entity("umami.Domain.Entities.USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CELULAR")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("COMPLEMENTO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CPF")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NUMENDERECO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SEQTIPOUSUARIO")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SEQTIPOUSUARIO");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("umami.Domain.Entities.VENDA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_VENDA")
                        .HasColumnType("datetime2");

                    b.Property<int>("SEQUSUARIO")
                        .HasColumnType("int");

                    b.Property<bool>("STATUS")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("SEQUSUARIO");

                    b.ToTable("VENDA");
                });

            modelBuilder.Entity("umami.Domain.Entities.ITENSVENDA", b =>
                {
                    b.HasOne("umami.Domain.Entities.PRODUTO", "PRODUTO")
                        .WithMany("ITENSVENDA")
                        .HasForeignKey("SEQPRODUTO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("umami.Domain.Entities.VENDA", "VENDA")
                        .WithMany("ITENSVENDA")
                        .HasForeignKey("SEQVENDA")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PRODUTO");

                    b.Navigation("VENDA");
                });

            modelBuilder.Entity("umami.Domain.Entities.USUARIO", b =>
                {
                    b.HasOne("umami.Domain.Entities.TIPOUSUARIO", "TIPOUSUARIO")
                        .WithMany("USUARIO")
                        .HasForeignKey("SEQTIPOUSUARIO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TIPOUSUARIO");
                });

            modelBuilder.Entity("umami.Domain.Entities.VENDA", b =>
                {
                    b.HasOne("umami.Domain.Entities.USUARIO", "USUARIO")
                        .WithMany("VENDAS")
                        .HasForeignKey("SEQUSUARIO")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("umami.Domain.Entities.PRODUTO", b =>
                {
                    b.Navigation("ITENSVENDA");
                });

            modelBuilder.Entity("umami.Domain.Entities.TIPOUSUARIO", b =>
                {
                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("umami.Domain.Entities.USUARIO", b =>
                {
                    b.Navigation("VENDAS");
                });

            modelBuilder.Entity("umami.Domain.Entities.VENDA", b =>
                {
                    b.Navigation("ITENSVENDA");
                });
#pragma warning restore 612, 618
        }
    }
}
